### ISSUE TITLE
Binary only supports 11.0 and up

### ISSUE THREAD

**Issue by mistyhands** [mistyhands/CrystalRCM#1]
This is due to the installer basing the bundled binaries on the installed version of python on my system (12.1).

Building with `MACOSX_DEPLOYMENT_TARGET` set to `10.9` results in a binary having a min version of 11.0.

**Comment by thenetstud** [comment]
Tested on Catalina 10.15.7 and the app failed to launch. Will keep an eye on this project incase it is supported in the future.

**Comment by mistyhands** [comment]
> Tested on Catalina 10.15.7 and the app failed to launch. Will keep an eye on this project incase it is supported in the future.

I'm honestly not sure why this is happening as all binaries and frameworks when inspected with otool now have a minimum build version of 10.9 in the [newest release](https://github.com/mistyhands/CrystalRCM/releases/tag/0.1.1). 

Could you possibly try (with version 0.1.1) posting the output of running `.../CrystalRCM.app/Contents/MacOS/CrystalRCM` from the terminal please?

**Comment by thenetstud** [comment]
> > Tested on Catalina 10.15.7 and the app failed to launch. Will keep an eye on this project incase it is supported in the future.
> 
> I'm honestly not sure why this is happening as all binaries and frameworks when inspected with otool now have a minimum build version of 10.9 in the [newest release](https://github.com/mistyhands/CrystalRCM/releases/tag/0.1.1).
> 
> Could you possibly try (with version 0.1.1) posting the output of running `.../CrystalRCM.app/Contents/MacOS/CrystalRCM` from the terminal please?

So I launched the CrystalRCM file from within the CrystalRCM.app/Contents/MacOS/ and it opened for me. Now opening the app itself works too. Strange, glad its working though.

**Comment by mistyhands** [comment]
> > > Tested on Catalina 10.15.7 and the app failed to launch. Will keep an eye on this project incase it is supported in the future.
> > 
> > I'm honestly not sure why this is happening as all binaries and frameworks when inspected with otool now have a minimum build version of 10.9 in the [newest release](https://github.com/mistyhands/CrystalRCM/releases/tag/0.1.1).
> > 
> > Could you possibly try (with version 0.1.1) posting the output of running `.../CrystalRCM.app/Contents/MacOS/CrystalRCM` from the terminal please?
> 
> So I launched the CrystalRCM file from within the CrystalRCM.app/Contents/MacOS/ and it opened for me. Now opening the app itself works too. Strange, glad its working though.

Ah glad to hear, maybe there was a mixup with the old version

**Comment by mistyhands** [comment]
fixed
