### ISSUE TITLE
0.1.2 Wont start up.  

### ISSUE THREAD

**Issue by skwiz0d** [mistyhands/CrystalRCM#5]
The old version worked besides the hanging after pushing but this new version wont even startup for me.  Says CrystalRCM is damaged and can't be opened.  You should move it to the Trash.

Any Ideas?

**Comment by mistyhands** [comment]
Sorry, I didn't have that issue on mine.. I'll have a proper look at it once I'm free. What macOS version are you on? also, intel or M1?

really sorry for this lol

**Comment by skwiz0d** [comment]
Shoot don't sweat it.  Im just happy to have something for macos.  :)

I'm on the Latest Ventura on a M1 Mac Mini.

**Comment by mistyhands** [comment]
> Shoot don't sweat it. Im just happy to have something for macos. :)
> 
> I'm on the Latest Ventura on a M1 Mac Mini.

hi ! could you please double check https://github.com/mistyhands/CrystalRCM/releases/tag/0.1.3 for me ? this should fix it !!

**Comment by skwiz0d** [comment]
Back in Business!  Thank you!
